### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by andreareed** [andreareed/indevr#5]
# Description 
Users can view all their submitted job in a single table that will be know as the Tracker.

- [ ] Show job list in a table
- [ ] Use a stripped table format for readability
- [ ] Display last activity in 'Days Ago' format
- [ ] Include a link on this page to add a job
- [ ] Paginate job list, displaying 25 per page

## Mocks
![tracker](https://user-images.githubusercontent.com/40516265/44305662-fee5d400-a331-11e8-98f2-1fe8dc1ac98e.jpg)
