### ISSUE TITLE
Job Tracker

### ISSUE THREAD

**Issue by andreareed** [andreareed/indevr#7]
# Description
Users can view a list of jobs they have entered on the Job Tracker.  

## ACs
- [x] The tracker will display the following in each row:
     * The date the job was added
     * The date of last activity by the user
     * The position the job is for
     * The company hiring for the position
     * The city and state where the job is located
     * The date the user applied for the job
- [x] Data can be sorted by any column
- [x] Default sort order is by date of activity, with oldest listed first
- [x] The tracker is paginated, showing 20 jobs per page
     - [x] Pagination is hidden if there are 20 jobs or less
- [x] An `Add Job` link is available at the top of the tracker

![indevr-mocks](https://user-images.githubusercontent.com/11544189/46907889-b9c3c580-cece-11e8-9e6d-af23e630d8ae.png)
